### PR TITLE
Create a Events website that implements complex association and database queries

### PR DESCRIPTION
**Pull request by anewman15**
In this PR, I
- generated, configured and created User Model, Controllers and Views and their corresponding routes
- generated, configured and created Event Model, Controllers and Views and their corresponding routes
- defined validations for User and Event models
- defined associations for User and Event models using has_many through
- create complex Active Record Queries using scopes
- created helper methods for user and event controllers
- tested model validations, associations and scopes using RSpec
- tested controller actions using RSpec
- carried out integrations tests using RSpec and Capybara

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested :red_circle: 

### Hello @anewman15 :wave: 

### Your project looks amazing, I really like the work you put in it, it's very beautiful! :smile: 

### Please, check my suggestions below:

- [ ] You have failing tests, please fix those:

Screenshot from 2020-10-13 16-15-26

- [x] Check your linter errors, the PR is appointing some, you should fix them!

- [ ] When I start your app, I can see a form for creating events even if I'm not signed in. I should only see this form if I am authorized to do so if I sign up or sign in.

- [x] The form fields are duplicated, please fix it. Check my screenshot below:

Screenshot from 2020-10-13 16-17-22

## Summary

- Very beautiful and well-implemented project :heart: 
- Your commit messages, README file, and PR are very professional :rocket: 
- We only need to fix those bugs before moving on :bug: 

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by anewman15** [comment]
Hi @MuriloRoque, I have made the first and third changes you asked for. I intend to keep the form in the index page and show it when the user is not logged in. It will allow the user to fill the form to create an event, but when they click the `Create Event` button, they are redirected to `Log In` page. I want to keep it that way because of information architecture ;)

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Require Changes :red_circle: 
### Great work implementing does changes, but there are some more work to do in order to get approved. :wink: 
__Check out my comments below__

- [ ] __EventActions:__ Only when a user is logged in Event#show displays the creator of the event
- [ ] __Linter:__ The buttom of your PR should show us no errors

# Happy Coding! :computer: :nerd_face:

**Comment by anewman15** [comment]
Hi @Dandush03, please check your Slack, I need some clarification

I have problem with your remarks:
1. EventActions: Only when a user is logged in Event#show displays the creator of the event
--- This is project is about cloning the functionality of EventBrite. And an user doesn't need to be logged in to see the host of the event. You can see here: https://www.eventbrite.com/e/2020-aint-cancelled-series-tickets-115239025026?aff=ebdssbcitybrowse

2. Linter: The buttom of your PR should show us no errors
--- The PR errors are from the failed tests when run by GitHub Actions. But when I run them on my machine, the tests all pass. I have no failing tests. All my 39 tests are passing. I tried re-running the tests on GitHub Actions, but they still give me 6 failing tests. I don't know how to fix that. I need your help with this
Screenshot from 2020-10-16 10-54-28

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
### Good so far Team :+1: However you need to consider the following issue :point_down:

- **_Fix the linter error: Try to identify the specified in the GitHub_**

#### _Reviewed by Temitayo Adeleke_

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

**Pull request merged**
